CREATE SCHEMA iso8583info;

CREATE TABLE log_iso(
	id_log_iso INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	element_log_iso INT,
    length_log_iso VARCHAR (25) CHARACTER SET utf8,
    description_log_iso VARCHAR (100) CHARACTER SET utf8
);

INSERT INTO log_iso VALUES
(DEFAULT, 1, 'b-8', 'Bit Map Secondary'),
(DEFAULT, 2, 'LLVAR', 'Primary Account Number'),
(DEFAULT, 3, 'n-6', 'Processing Code'),
(DEFAULT, 4, 'n-12', 'Amount, Transaction'),
(DEFAULT, 5, 'n-12', 'Amount, Settlement'),
(DEFAULT, 6, 'n-12', 'Amount, Cardholder'),
(DEFAULT, 7, 'n-10', 'Transmission Date and Time'),
(DEFAULT, 8, 'n-8', 'Amount, Cardholder Billing Fee'),
(DEFAULT, 9, 'n-8', 'Conversion Rate, Settlement'),
(DEFAULT, 10, 'n-8', 'Conversion Rate, Cardholder Billing'),
(DEFAULT, 11, 'n-6', 'Systems Trace Audit Number'),
(DEFAULT, 12, 'n-6', 'Time, Local Transaction'),
(DEFAULT, 13, 'n-4', 'Date, Local Transaction'),
(DEFAULT, 14, 'n-4', 'Date, Expiration'),
(DEFAULT, 15, 'n-4', 'Date, Settlement'),
(DEFAULT, 16, 'n-4', 'Date, Conversion'),
(DEFAULT, 17, 'n-4', 'Date, Capture'),
(DEFAULT, 18, 'n-4', 'Merchant Type'),
(DEFAULT, 19, 'n-3', 'Acquiring Institution Country Code'),
(DEFAULT, 20, 'n-3', 'Primary Account Number (PAN) Country'),
(DEFAULT, 21, 'n-3', 'Forwarding Institution Country Code'),
(DEFAULT, 22, 'n-3', 'Point-of-Service'),
(DEFAULT, 23, 'n-3', 'Card Sequence Number'),
(DEFAULT, 24, 'n-3', 'Network International ID7'),
(DEFAULT, 25, 'n-2', 'Point-of-Service (POS) Condition Code7'),
(DEFAULT, 26, 'n-2', 'Point-of-Service (POS) Personal ID Number (PIN) Capture Code'),
(DEFAULT, 27, 'n-1', 'Authorization ID Response Length7'),
(DEFAULT, 28, 'an-9', 'Amount, Transaction Fee'),
(DEFAULT, 29, 'an-9', 'Amount, Settlement Fee7'),
(DEFAULT, 30, 'an-9', 'Amount, Transaction Processing Fee7'),
(DEFAULT, 31, 'an-9', 'Amount, Settlement Processing Fee7'),
(DEFAULT, 32, 'n…6; LLVAR', 'Acquiring Institution ID Code'),
(DEFAULT, 33, 'n…6; LLVAR', 'Forwarding Institution ID Code'),
(DEFAULT, 34, 'ans…28; LLVAR', 'Primary Account Number (PAN), DEFAULT, Extended7'),
(DEFAULT, 35, 'ans…37; LLVAR', 'Track 2 Data'),
(DEFAULT, 36, 'ans…104; LLLVAR', 'Track 3 Data7'),
(DEFAULT, 37, 'n-12', 'Retrieval Reference Number'),
(DEFAULT, 38, 'ans-6', 'Authorization ID Response'),
(DEFAULT, 39, 'an-2', 'Response Code'),
(DEFAULT, 40, 'an-3', 'Service Restriction'),
(DEFAULT, 41, 'ans-8', 'Card Acceptor Terminal ID'),
(DEFAULT, 42, 'ans-15', 'Card Acceptor ID Code'),
(DEFAULT, 43, 'ans-40', 'Card Acceptor Name/Location'),
(DEFAULT, 44, 'ans…25; LLVAR', 'Additional Response Data'),
(DEFAULT, 45, 'ans…76; LLVAR', 'Track 1 Data'),
(DEFAULT, 46, 'ans…999; LLLVAR', 'Additional Data—ISO Use7'),
(DEFAULT, 47, 'ans…999; LLLVAR', 'Additional Data—National Use8'),
(DEFAULT, 48, 'ans…999; LLLVAR', 'Additional Data—Private Use'),
(DEFAULT, 49, 'n-3', 'Currency Code, Transaction'),
(DEFAULT, 50, 'n-3', 'Currency Code, Settlement'),
(DEFAULT, 51, 'n-3', 'Currency Code, Cardholder Billing'),
(DEFAULT, 52, 'b-8', 'Personal ID Number (PIN) Data'),
(DEFAULT, 53, 'n-16', 'Security-Related Control Information'),
(DEFAULT, 54, 'an…240; LLLVAR', 'Additional Amounts'),
(DEFAULT, 55, 'b…255; LLLVAR', 'Integrated Circuit Card (ICC) System-Related Data'),
(DEFAULT, 56, 'an…37; LLLVAR', 'Payment Account Data'),
(DEFAULT, 57, 'NA', 'Reserved for National Use8'),
(DEFAULT, 58, 'NA', 'Reserved for National Use8'),
(DEFAULT, 59, 'NA', 'Reserved for National Use8'),
(DEFAULT, 60, 'ans…060; LLLVAR', 'Advice Reason Code10'),
(DEFAULT, 61, 'an…026; LLLVAR', 'Point-of-Service (POS) Data'),
(DEFAULT, 62, 'ans…100; LLLVAR', 'Intermediate Network Facility'),
(DEFAULT, 63, 'an…050; LLLVAR', 'Network Data10'),
(DEFAULT, 64, 'b-8', 'Message Authentic'),
(DEFAULT, 65, 'b-8', 'Bit Map, Extended'),
(DEFAULT, 66, 'n-1', 'Settlement Code7'),
(DEFAULT, 67, 'n-2', 'Extended Payment Code7'),
(DEFAULT, 68, 'n-3', 'Receiving Institution Country'),
(DEFAULT, 69, 'n-3', 'Settlement Institution Country Code'),
(DEFAULT, 70, 'n-3', 'Network Management Information Code'),
(DEFAULT, 71, 'n-4', 'Message Number7'),
(DEFAULT, 72, 'n-4', 'Message Number Last7'),
(DEFAULT, 73, 'n-6', 'Date, Action'),
(DEFAULT, 74, 'n-10', 'Credits, Number7'),
(DEFAULT, 75, 'n-10', 'Credits, Reversal'),
(DEFAULT, 76, 'n-10', 'Debits, Number7'),
(DEFAULT, 77, 'n-10', 'Debits, Reversal'),
(DEFAULT, 78, 'n-10', 'Transfers, Number'),
(DEFAULT, 79, 'n-10', 'Transfers, Reversal Number'),
(DEFAULT, 80, 'n-10', 'Inquiries, Number'),
(DEFAULT, 81, 'n-10', 'Authorizations, Number7'),
(DEFAULT, 82, 'n-12', 'Credits, Processing Fee Amount7'),
(DEFAULT, 83, 'n-12', 'Credits, Transaction Fee Amount7'),
(DEFAULT, 84, 'n-12', 'Debits, Processing Fee Amount7'),
(DEFAULT, 85, 'n-12', 'Debits, Transaction Fee Amount7'),
(DEFAULT, 86, 'n-16', 'Credits, Amount7'),
(DEFAULT, 87, 'n-16', 'Credits, Reversal Amount7'),
(DEFAULT, 88, 'n-16', 'Debits, Amount7'),
(DEFAULT, 89, 'n-16', 'Debits, Reversal Amount7'),
(DEFAULT, 90, 'n-42', 'Original Data Elements'),
(DEFAULT, 91, 'an-1', 'Issuer File Update Code'),
(DEFAULT, 92, 'an-2', 'File Security Code7'),
(DEFAULT, 93, 'an-5', 'Response Indicator7'),
(DEFAULT, 94, 'an-7', 'Service Indicator'),
(DEFAULT, 95, 'n-42', 'Replacement Amounts'),
(DEFAULT, 96, 'b-8', 'Message Security Code10'),
(DEFAULT, 97, 'n-17', 'Amount, Net Settlement7'),
(DEFAULT, 98, 's-25', 'Payee'),
(DEFAULT, 99, 'LVAR', 'Settlement Institution ID'),
(DEFAULT, 100, 'LVAR', 'Receiving Institution ID Code n'),
(DEFAULT, 101, 'ans…17; LLVAR', 'File Name'),
(DEFAULT, 102, 'ans…28; LLVAR', 'Account ID-1'),
(DEFAULT, 103, 'ans…28; LLVAR', 'Account ID-2'),
(DEFAULT, 104, 'ans...999; LLLVAR', 'Digital Payment Data7'),
(DEFAULT, 105, 'ans…999; LLLVAR', 'Reserved for Mastercard Use7'),
(DEFAULT, 106, 'null', 'null'),
(DEFAULT, 107, 'LVAR', 'Reserved for Mastercard Use7'),
(DEFAULT, 108, 'LVAR', 'Additional Transaction Reference Data'),
(DEFAULT, 109, 'LVAR', 'Reserved for ISO Use7'),
(DEFAULT, 110, 'LVAR', 'Additional Data—2'),
(DEFAULT, 111, 'LVAR', 'Reserved for ISO Use7'),
(DEFAULT, 112, 'LVAR', 'Additional Data (National Use)'),
(DEFAULT, 113, 'LVAR', 'Reserved for Future Use'),
(DEFAULT, 114, 'null', 'null'),
(DEFAULT, 115, 'null', 'null'),
(DEFAULT, 116, 'null', 'null'),
(DEFAULT, 117, 'null', 'null'),
(DEFAULT, 118, 'null', 'null'),
(DEFAULT, 119, 'null', 'null'),
(DEFAULT, 120, 'LVAR', 'Record Data10'),
(DEFAULT, 121, 'LVAR', 'Authorizing Agent ID Code10'),
(DEFAULT, 122, 'LVAR', 'Additional Record Data10'),
(DEFAULT, 123, 'LVAR', 'Receipt Free Text'),
(DEFAULT, 124, 'LVAR', 'Member-defined Data'),
(DEFAULT, 125, 'b-8', 'New PIN Data'),
(DEFAULT, 126, 'LVAR', 'Private Data'),
(DEFAULT, 127, 'LVAR', 'Private Data10'),
(DEFAULT, 128, 'b-8', 'Message Authentication Code (MAC)'),
(DEFAULT, DEFAULT, 'b-8', 'Message Type Identifier (MTI)');